/*

This is a JavaScript file you can edit to add custom markers to the map.
uNmINeD does not overwrite this file during map generation.

Steps:

    1. Edit this file using Notepad or a code editor (do not use document editors like Microsoft Word)
    2. Change the line "isEnabled: false," to "isEnabled: true," to display the markers
    3. Change or remove the example markers
    4. Add your own markers

Marker format:

    {
        x: X coordinate of the marker (in Minecraft block units),
        z: Z coordinate of the marker (in Minecraft block units),
        image: marker image URL to display (in quotes),
        imageScale: scale of the image (e.g. 1 = display full size, 0.5 = display half size),
        imageAnchor: [0.5, 1] means the tip of the pin is at the center-bottom of the image (see OpenLayers documentation for more info),
        text: marker text do display (in quotes),
        textColor: text color in HTML/CSS format (in quotes),
        offsetX: horizontal pixel offset of the text,
        offsetY: vertical pixel offset of the text,
        font: text font in HTML/CSS format (in quotes),
    },

Things to keep in mind:

* There are opening and closing brackets for each marker "{" and "}"
* Property names are case sensitive (i.e. "textColor" is okay, "TextColor" is not)
* There is a comma (",") at the end of each line except the opening brackets ("{")

You can use https://mapmarker.io/editor to generate custom pin images.
Use the imageScale property if the pin image is too large.

*/
var line1Color = "#253B94";
var line2Color = "#3AB449";
var line3Color = "#dc5700";
var line4Color = "#1b91bf";

var cultureColor = "#BD91BD";
var heritageColor = "#A2895F";
var hospitalColor = "#FBCECE";
var hotelColor = "#D6C8FF";
var houseColor = "#D9BC98";
var natureColor = "#C5FFAC";
var restaurantColor = "#FFC36F";
var sportColor = "#CDFDFD";
var universityColor = "#8CCFF9";

UnminedCustomMarkers = {

    isEnabled: true,

    markers: [

        /*
        // Example 1: Simple marker
        {
            x: -200,
            z: -200,
            image: "pinImages/custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
        },

        // Example 2: Marker with text
        {
            x: 0,
            z: 0,
            image: "pinImages/custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Marker with text",
            textColor: "red", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
        },

        // Example 3: Text only
        {
            x: 200,
            z: 200,
            text: "Text only", 
            textColor: "yellow", 
            offsetX: 0,
            offsetY: 0, 
            font: "bold 50px Calibri,sans serif",
        },
        */
        // add your markers here
        //ㄱ
        {
            x: 1773,
            z: -1393,
            image: "pinImages/mountain.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "갑산",
            textColor: natureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 2114,
            z: -1407,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "갑산감옥",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 868,
            z: -8,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "강동문",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 1500,
            z: 300,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "강설부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: 269,
            z: -143,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "건축대학",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -318,
            z: -264,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "건축부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -953,
            z: 87,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "경용대학교",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 302,
            z: 465,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "고등법원",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 303,
            z: -370,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "공과대학",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 938,
            z: -438,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "공군사관학교",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
        },
        {
            x: 925,
            z: -496,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "공사역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -21,
            z: -154,
            text: "과학연구센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: -9,
            z: -106,
            text: "구공학관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: 1126,
            z: 1046,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "구룡성채",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -237,
            z: -372,
            image: "pinImages/theater.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "국립극장",
            textColor: cultureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -573,
            z: -372,
            image: "pinImages/museum.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "국립박물관",
            textColor: cultureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -153,
            z: 288,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "국방부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -731,
            z: -383,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "국제금융센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 326,
            z: 607,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "국회도서관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 197,
            z: 390,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "국회역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -600,
            z: 390,
            image: "pinImages/park.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "궐내공원",
            textColor: natureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -533,
            z: -257,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "근대자동차",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1279,
            z: 1171,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "근대자동차공장",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -215,
            z: 1450,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "금성루 남해(예정)",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -254,
            z: -205,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "금융공유오피스",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: 3500,
            z: -1500,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "금청부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: 333,
            z: 123,
            image: "pinImages/restaurant.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "김밥제국",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },

        //ㄴ
        {
            x: 423,
            z: 1275,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "나성 청해(예정)",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1322,
            z: 1533,
            image: "pinImages/line4.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "남성유역",
            textColor: "white",
            textStrokeColor: line4Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -700,
            z: 2432,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "남진동",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: -900,
            z: -600,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "남해건설",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -83,
            z: 1045,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "남해동",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: 15,
            z: 1584,
            image: "pinImages/port.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "남해여객터미널",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 197,
            z: 1533,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "남해역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
        },
        {
            x: -474,
            z: 1279,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "너울채(예정)",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 66,
            z: -158,
            text: "노천극장",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: 262,
            z: 1256,
            image: "pinImages/hotel.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "능하 호텔(예정)",
            textColor: hotelColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },

        //ㄷ
        {
            x: -252,
            z: -170,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "달태제과",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -102,
            z: -321,
            text: "대운동장",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: -84,
            z: 45,
            image: "pinImages/restaurant.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "대학포차",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 197,
            z: -85,
            text: "대한문",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: 136,
            z: 81,
            image: "pinImages/restaurant.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "던킹도너츠",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: -1400,
            z: 390,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "도민궁",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
        },
        {
            x: -391,
            z: 390,
            image: "pinImages/line3.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "도민궁역",
            textColor: "white",
            textStrokeColor: line3Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 1279,
            z: 1249,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "도요새공장",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -483,
            z: 392,
            text: "돈화문",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: 653,
            z: -8,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "동대문",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1000,
            z: -3000,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "동명부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },

        //ㄹ
        {
            x: 76,
            z: 1267,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "레켄스 포레",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -33,
            z: 1277,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "레켄스 타워",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 2518,
            z: -2096,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "리퍼블릭오브수민",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },

        //ㅁ
        {
            x: 144,
            z: -114,
            text: "마법사의 집",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: -467,
            z: -264,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "마크타임즈",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 138,
            z: 121,
            image: "pinImages/restaurant.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "명량한 핫도그",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 197,
            z: -1200,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "명륜당",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 197,
            z: 929,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "문화전시관역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 1700,
            z: -1800,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "미수부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: 2300,
            z: -2000,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "미지정",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: -813,
            z: 390,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "민화문",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },

        //ㅂ
        {
            x: 2248,
            z: -2361,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "바다신전",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -508,
            z: 173,
            image: "pinImages/theater.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "밸로보그극장",
            textColor: cultureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 157,
            z: 39,
            image: "pinImages/fastfood.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "버거황",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 2120,
            z: 1457,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "버크셔경용웨이",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: 85,
            z: 17,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "보신각",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -718,
            z: 20,
            text: "북궁호",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: -2400,
            z: -720,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "북위동",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: -650,
            z: -650,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "북해동",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: -320,
            z: -134,
            image: "pinImages/goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "북해동주민센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -831,
            z: -499,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "북해역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 967,
            z: 321,
            image: "pinImages/mountain.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "빙산",
            textColor: natureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },

        //ㅅ
        {
            x: 1117,
            z: -1107,
            image: "pinImages/mountain.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "삼수",
            textColor: natureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1193,
            z: -8,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "서래타워",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
        },
        {
            x: -3000,
            z: 800,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "서문동",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: -976,
            z: -102,
            image: "pinImages/goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "서문동주민센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -1206,
            z: 288,
            image: "pinImages/mountain.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "서악산",
            textColor: natureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -703,
            z: 1280,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "선세계 남해(예정)",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -391,
            z: 1365,
            image: "pinImages/line4.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "지수역",
            textColor: "white",
            textStrokeColor: line4Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -1000,
            z: 3500,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성남구",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 3,
            maxZoom: 4,
        },
        {
            x: -1000,
            z: 0,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성내구",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 3,
            maxZoom: 4,
        },
        {
            x: 385,
            z: 142,
            image: "pinImages/goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성내구청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
        },
        {
            x: 71,
            z: 486,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성내중앙지방검찰청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 1271,
            z: 301,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성동경찰청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1915,
            z: 106,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성동구",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 3,
            maxZoom: 4,
        },
        {
            x: 2161,
            z: -2166,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성동구의회",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
            info: "성동구에서 있는 유일한 사원이자 의회이다. 과거 미지국에 온 이방인이 지어준 건물이다. 원래는 미지국의 수도로 사용되었으나, 이슬람제국에 점령당한 후 이들은 모스크로 개조당했다. 이후 수민국에 점령된 후 방치되었으나, 성동구 산하에 넘어간 후 무너진 건물을 복원한 후, 의회로 사용중이다. 다만 이슬람 인원들에 의해 라마단 기간에는 의회활동을 멈추고 이슬람교도들을 위해 자리를 비워준다.",
        },
        {
            x: 1769,
            z: 1114,
            image: "pinImages/goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성동구청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
            info: "성동구 행정을 맡는 성동구청입니다.",
        },
        {
            x: 1987,
            z: 1181,
            image: "pinImages/stadium.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성동성경기장",
            textColor: sportColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
            info: "성동구에 있는 성동성경기장이다. 주로 축구 경기가 열리며, 성동구민들의 휴식처로 알려져 있다.",
        },
        {
            x: 1119,
            z: 941,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성동시민아파트",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
            info: "성동구에 있는 성동시민아파트이다. 성동구민들의 주거지로 알려져 있다.",
        },
        {
            x: -1000,
            z: -3500,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성북구",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 3,
            maxZoom: 4,
            info: "성북구는 수민특별시의 5개 구 중 하나로, 수민특별시의 북쪽에 위치해 있다. 수민시의 주거지로 알려져 있다.",
        },
        {
            x: -4000,
            z: 0,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성서구",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 3,
            maxZoom: 4,
        },
        {
            x: 1300,
            z: 1300,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성호부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: -734,
            z: -247,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "세이버",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -734,
            z: -168,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "세이버 제2본사",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1196,
            z: -233,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "소환신전",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -924,
            z: -253,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수경 본사",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -1045,
            z: -260,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수경통신",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -752,
            z: 1100,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수려풍경 레이크(예정)",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 117,
            z: 551,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민고등검찰청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 197,
            z: -1118,
            text: "수민관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: 197,
            z: -496,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민대역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 349,
            z: -496,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민대역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 197,
            z: -1079,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민대학교",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
        },
        {
            x: -163,
            z: -97,
            image: "pinImages/hospital.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민대학교병원",
            textColor: hospitalColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 400,
            z: 929,
            image: "pinImages/theater.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민문화전시관",
            textColor: cultureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -80,
            z: 929,
            image: "pinImages/park.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민숲",
            textColor: natureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
        },
        {
            x: -391,
            z: 929,
            image: "pinImages/line3.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민숲역",
            textColor: "white",
            textStrokeColor: line3Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -330,
            z: -190,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민은행",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1249,
            z: 1101,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민전력공사",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 1920,
            z: 971,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민주택공사",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -297,
            z: 609,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민특별시",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 0,
            maxZoom: 2,
        },
        {
            x: -298,
            z: 611,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민특별시의회",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -268,
            z: 493,
            image: "pinImages/goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민특별시청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 8,
        },
        {
            x: 332,
            z: 34,
            image: "pinImages/cafe.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "스타벅스",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 400,
            z: -400,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "시교동",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: 0,
            z: 200,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "시작동",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: 44,
            z: 7,
            image: "pinImages/goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "시작동주민센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 197,
            z: -17,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "시작역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
        },
        {
            x: 154,
            z: 246,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "시작오피스텔",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1296,
            z: -8,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "신설산역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
        },
        {
            x: -338,
            z: 55,
            image: "pinImages/cafe.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "신코아백화점",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },

        //ㅇ
        {
            x: -311,
            z: 293,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "안전부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -92,
            z: -176,
            text: "약학관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: -2400,
            z: 1500,
            image: "pinImages/line4.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "연산역",
            textColor: "white",
            textStrokeColor: line4Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 800,
            z: -2000,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "연월부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: -2000,
            z: 1775,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "연해동",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: -1600,
            z: 1365,
            image: "pinImages/line4.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "연해역",
            textColor: "white",
            textStrokeColor: line4Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        //환구단 옆
        {
            x: -549,
            z: -12,
            text: "연희천",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        //cn건설 아래
        {
            x: -255,
            z: -46,
            text: "연희천",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: 158,
            z: 168,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "연희오피스텔",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: 249,
            z: 32,
            image: "pinImages/cafe.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "올리브제로",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -83,
            z: 602,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "외교부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1195,
            z: 353,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "우정국",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 2612,
            z: -1973,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "위령사",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
            info: "과거 미지도호부가 있던 자리였으나 전란으로 인해 불타 사라진 자리에 다시 세워진 건물이다. 미지정의 그 역사를 존중하여 성내구에서 기존의 도민궁에 쓰이던 건축물을 제공하였다. 즉 이 건물이 도민궁에 있는 것에 원조이다. 안에 있는 왕좌는 아무도 앉을 수 없는데, 이는 국가유공자의 넋만이 앉을 수 있다는 의미이기도 하다.",
        },
        {
            x: -487,
            z: -141,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "은성 본사",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -917,
            z: -396,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "은하은행",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -108,
            z: -100,
            text: "의학관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: 286,
            z: -231,
            text: "이학관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },

        //ㅈ
        {
            x: 287,
            z: -247,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "자연과학대학",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -128,
            z: 528,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "정부청사본관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
            info: "행정부 기관들이 머무는 정부청사본관입니다.",
        },
        {
            x: -90,
            z: 385,
            text: "정부청사단지",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 2319,
            z: 1300,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "정표모건빌딩",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 249,
            z: 165,
            image: "pinImages/fastfood.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "조테리아",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -1010,
            z: -383,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "조테 본사",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1940,
            z: 1367,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중국은행",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -1200,
            z: 250,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중명동",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: 197,
            z: -1017,
            text: "중명전",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: -758,
            z: -447,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중소기업센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 51,
            z: -206,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중앙도서관",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -391,
            z: -496,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중앙역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
        },
        {
            x: -391,
            z: -458,
            image: "pinImages/line3.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중앙역",
            textColor: "white",
            textStrokeColor: line3Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: -252,
            z: -257,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중앙오피스텔",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -524,
            z: 1118,
            text: "지석호",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: -531,
            z: 771,
            text: "지수호",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1103,
            z: 469,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "진리극지연구소",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1278,
            z: 456,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "진리지질연구소",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1452,
            z: 810,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "진리천문연구소",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },

        //ㅊ
        {
            x: 2505,
            z: -908,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "천관공항",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
        },
        {
            x: 2400,
            z: -600,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "천풍부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: 1881,
            z: -1090,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "천풍한옥마을",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 330,
            z: 390,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "청와당",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 2307,
            z: 1540,
            image: "pinImages/port.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "청해여객터미널",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: 857,
            z: 1087,
            image: "pinImages/port.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "청해항",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 5,
            maxZoom: 8,
        },
        {
            x: 316,
            z: -78,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "춘건루",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -734,
            z: -591,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "칠성 본사",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },

        //ㅋ
        {
            x: 142,
            z: 853,
            image: "pinImages/hotel.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "콘래드호텔",
            textColor: hotelColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -235,
            z: 1280,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "크리뉴 포레",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },

        //ㅌ
        {
            x: 44,
            z: 1447,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "탑궁",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },

        //ㅍ
        {
            x: 235,
            z: 290,
            image: "pinImages/bakery.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "파리바게트",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 146,
            z: 1094,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "파인애플스토어",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },

        //ㅎ
        {
            x: 47,
            z: -311,
            text: "학생회관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: 1794,
            z: 839,
            image: "pinImages/mountain.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "화악산",
            textColor: natureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -326,
            z: 5,
            image: "pinImages/restaurant.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "황금고깃집",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 2363,
            z: -1973,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "현충원",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 2212,
            z: 1068,
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "호반정",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
            minZoom: 4,
            maxZoom: 6,
        },
        {
            x: -472,
            z: 15,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "환구단",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: -499,
            z: -3,
            text: "황궁우",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },

        //ABC
        {
            x: 2119,
            z: 1382,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "ABC건설",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 252,
            z: 124,
            image: "pinImages/cafe.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "catdog애견애묘",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 8,
            maxZoom: 8,
        },
        {
            x: 2183,
            z: 1457,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "EIFC",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 6,
            maxZoom: 8,
        },
        {
            x: -249,
            z: -116,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "CN건설",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1271,
            z: 231,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "EES",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1194,
            z: 268,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "HBC",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 2037,
            z: 1478,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "HSBD",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1865,
            z: 1037,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "KY건설",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 139,
            z: 322,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "M&M로펌",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },
        {
            x: 1243,
            z: 591,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "STEAM",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
            minZoom: 7,
            maxZoom: 8,
        },



        // do not delete the following two closing brackets
    ]
}
